### ISSUE TITLE
Describe style of application

### ISSUE THREAD

**Issue by YuliaNastiushkina** [ios-course/link-team-project#14]
Add list of style criteria to the [wiki](https://github.com/ios-course/link-team-project/wiki/App-style-guidelines).
- font of text;
- style of button;
- colors to use in app.

**Comment by YuliaNastiushkina** [comment]
@kirpichonok @levvaa you can check that issue

**Comment by levvaa** [comment]
We have only heading and body fonts? We don't need smaller fonts? For example that used inside elements.

**Comment by levvaa** [comment]
lgtm

**Comment by kirpichonok** [comment]
The issue was done by @YuliaNastiushkina.
