### ISSUE TITLE
Set up environment 

### ISSUE THREAD

**Issue by kirpichonok** [ios-course/link-team-project#2]
**AC:** 
- create the `.gitignore` file. 
It should exclude files generated by macOS like `DS_Store` and generated by Xcode related to the user `xcuserdata/`.
```
# Xcode

## User settings
xcuserdata/
timeline.xctimeline 

## OS generated files
.DS_Store
```
  
- add empty CHANGELOG.md 
- add empty Rеlease notes file

- format of the [CHANGELOG.md](https://keepachangelog.com/en/1.0.0/)
Example: 
```
# CHANGELOG

All notable changes to this project will be documented in this file.

## [unreleased version]

### Added
```

- format of the Release notes:

```
Version x.x.x
Release date dd.mm.yyyy

## What changed ?
1. Feature1
2. Feature2
3. BugFix1
4. ...
```

**Comment by levvaa** [comment]
I want to use format without timeline.xctimeline.
I propose the final look: 

```
## OS generated files
.DS_Store

# Xcode

## User settings
xcuserdata/
```

@kirpichonok @YuliaNastiushkina Are you agree?

**Comment by YuliaNastiushkina** [comment]
Can you tell why? What are your arguments?

**Comment by levvaa** [comment]
@kirpichonok because this files used only for playgrounds files. 
Using this format only for a project file is useless.

**Comment by YuliaNastiushkina** [comment]
Thanks, I agree with your version of .gitignore.

**Comment by kirpichonok** [comment]
PR #25 is merged so the issue is closed.
