### ISSUE TITLE
Create UI for History of Operations screen.

### ISSUE THREAD

**Issue by kirpichonok** [ios-course/link-team-project#3]
### This issue has next subtasks: 

- [x] #42
- [x] #43
- [x] #44
- [x] #47

### Task description
List contains information about all already created bills. One line shows one bill and contains information about participants, short description and sum of the bill. Also above the list of accounts there should be a display of the date. If multiple invoices are created on the same date, they are listed from newest to oldest on top of them. Scroll view must be used for the list.

Fonts style based on [App style guidelines ](https://github.com/ios-course/link-team-project/wiki/App-style-guidelines)

The image with a scheme of the screen:
<img width="356" alt="Screenshot 2023-05-23 at 12 49 52" src="https://github.com/ios-course/link-team-project/assets/120186417/bb773635-abcb-4266-8e6f-b636b8ba0a0b">

**Comment by YuliaNastiushkina** [comment]
Good job.

Please, fix typo Scheme instead Sheme.

Max length of description may be 15 characters, what of you think ? @kirpichonok do you have any suggestions ?
I think that we don't need button "more", at least for now.
Font you can see in [App style guidelines](https://github.com/ios-course/link-team-project/wiki/App-style-guidelines).
